# syntax=docker/dockerfile:1

FROM python:3.12.4-slim-bookworm

WORKDIR /python-docker

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 8080
ENTRYPOINT ["python", "app.py"]